In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import mean_squared_error
from sklearn import linear_model

In [2]:
df_train = pd.read_csv("Datasets\weatherHistory\weatherHistory_Train.csv")
df_train = pd.DataFrame(df_train)
df_test = pd.read_csv("Datasets\weatherHistory\weatherHistory_Test.csv")
df_test = pd.DataFrame(df_test)
df_train.head()

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,2006-04-01 00:00:00.000 +0200,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,2006-04-01 01:00:00.000 +0200,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,2006-04-01 02:00:00.000 +0200,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,2006-04-01 03:00:00.000 +0200,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,2006-04-01 04:00:00.000 +0200,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.

In [3]:
df_train.isnull()
df_train.isna().sum()

Formatted Date                0
Summary                       0
Precip Type                 143
Temperature (C)               0
Apparent Temperature (C)      0
Humidity                      0
Wind Speed (km/h)             0
Wind Bearing (degrees)        0
Visibility (km)               0
Loud Cover                    0
Pressure (millibars)          0
Daily Summary                 0
dtype: int64

In [4]:
df_test.isnull()
df_test.isna().sum()

Formatted Date              0
Summary                     0
Precip Type               374
Temperature (C)             0
Humidity                    0
Wind Speed (km/h)           0
Wind Bearing (degrees)      0
Visibility (km)             0
Loud Cover                  0
Pressure (millibars)        0
Daily Summary               0
dtype: int64

In [5]:
import datetime as dt
df_train['Formatted Date'] = pd.to_datetime(df_train['Formatted Date'])
df_train['Formatted Date']=df_train['Formatted Date'].map(dt.datetime.toordinal)

df_test['Formatted Date'] = pd.to_datetime(df_test['Formatted Date'])
df_test['Formatted Date']=df_test['Formatted Date'].map(dt.datetime.toordinal)

In [6]:
df_train

,Formatted Date,Summary,Precip Type,Temperature (C),Apparent Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars),Daily Summary
0,732402,Partly Cloudy,rain,9.472222,7.388889,0.89,14.1197,251.0,15.8263,0.0,1015.13,Partly cloudy throughout the day.
1,732402,Partly Cloudy,rain,9.355556,7.227778,0.86,14.2646,259.0,15.8263,0.0,1015.63,Partly cloudy throughout the day.
2,732402,Mostly Cloudy,rain,9.377778,9.377778,0.89,3.9284,204.0,14.9569,0.0,1015.94,Partly cloudy throughout the day.
3,732402,Partly Cloudy,rain,8.288889,5.944444,0.83,14.1036,269.0,15.8263,0.0,1016.41,Partly cloudy throughout the day.
4,732402,Mostly Cloudy,rain,8.755556,6.977778,0.83,11.0446,259.0,15.8263,0.0,1016.51,Partly cloudy throughout the day.
...,...,...,...,...,...,...,...,...,...,...,...,...
67512,735008,Mostly Cloudy,rain,17.594444,17.594444,0.84,10.6421,279.0,9.9820,0.0,1010.25,Partly cloudy throughout the day.
67513,735008,Partly Cloudy,rain,17.566667,17.566667,0.80,13.5723,269.0,11.0285,0.0,1011.30,Partly cloudy throughout the day.
67514,735008,Partly Cloudy,rain,17.000000,17.000000,0.81,14.0392,260.0,15.8263,0.0,1011.82,Partly cloudy throughout the day.
67515,735008,Partly Cloudy,rain,15.355556,15.355556,0.78,14.0231,250.0,15.8263,0.0,1011.83,Partly cloudy throughout the day.
67516,735008,Partly Cloudy,rain,14.272222,14.272222,0.85,10.7065,227.0,14.9569,0.0,1012.85,Partly cloudy throughout the day.

In [7]:
df_train["Summary"].value_counts()
df_test["Summary"].value_counts()

Mostly Cloudy               9825
Partly Cloudy               8771
Overcast                    5489
Clear                       2354
Foggy                       1941
Breezy and Overcast          177
Breezy and Mostly Cloudy     134
Breezy and Partly Cloudy      71
Light Rain                    46
Drizzle                       34
Breezy                        22
Humid and Mostly Cloudy       13
Dry and Partly Cloudy         11
Windy and Partly Cloudy       11
Rain                          10
Windy and Mostly Cloudy        8
Windy and Overcast             7
Windy                          4
Humid and Overcast             4
Breezy and Foggy               2
Windy and Foggy                1
Dry                            1
Name: Summary, dtype: int64

In [8]:
df_train["Precip Type"].value_counts()
df_test["Precip Type"].isna().sum()
df_test["Precip Type"].value_counts()
df_train["Precip Type"]

0        rain
1        rain
2        rain
3        rain
4        rain
         ...
67512    rain
67513    rain
67514    rain
67515    rain
67516    rain
Name: Precip Type, Length: 67517, dtype: object

In [9]:
# df_train["Precip Type"].fillna("block", inplace=True)
# df_test["Precip Type"].fillna("block", inplace=True)
temp_Xtrain=df_test["Precip Type"].dropna()
temp_Xtest=df_test["Precip Type"].dropna()

# Precip_Type = {'snow': 2,'rain': 1} 
# temp_Xtrain["Precip Type"] = [Precip_Type[item] for item in temp_Xtrain["Precip Type"]]
# temp_Xtest["Precip Type"] = [Precip_Type[item] for item in temp_Xtest["Precip Type"]]

mode_Xtrain = temp_Xtrain.mode()
mode_Xtest = temp_Xtest.mode()
print(mode_Xtest)

df_train["Precip Type"].fillna(mode_Xtrain[0], inplace=True)
df_test["Precip Type"].fillna(mode_Xtest[0], inplace=True)

Precip_Type = {'snow': 2,'rain': 1} 
df_train["Precip Type"] = [Precip_Type[item] for item in df_train["Precip Type"]]
df_test["Precip Type"] = [Precip_Type[item] for item in df_test["Precip Type"]]

0    rain
Name: Precip Type, dtype: object

In [10]:
# print((mode_Xtest[0]))

In [11]:
# df_train["Precip Type"].isna().sum()

In [12]:
# df_train

In [13]:
# df_test["Precip Type"].isna().sum()
# df_test.to_csv("emp.csv")

In [14]:
x_train = df_train.drop(["Summary","Daily Summary","Apparent Temperature (C)","Loud Cover"], axis=1)
y_train = pd.DataFrame(df_train["Apparent Temperature (C)"])
x_test = df_test.drop(["Summary","Daily Summary","Loud Cover"], axis=1)

In [15]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.preprocessing import PolynomialFeatures

# poly = PolynomialFeatures(2)
# poly.fit_transform(x_train)
# poly_test = PolynomialFeatures(2)
# poly_test.fit_transform(x_test)

x_train_values = x_train.values #returns a numpy array
min_max_scaler = StandardScaler()

x_scaled_train = min_max_scaler.fit_transform(x_train_values)
x_train = pd.DataFrame(x_scaled_train,columns = x_train.columns)

x_test_values = x_test.values #returns a numpy array
min_max_scaler = StandardScaler()
x_scaled_test = min_max_scaler.fit_transform(x_test_values)
x_test = pd.DataFrame(x_scaled_test,columns = x_test.columns)

In [16]:
x_train

,Formatted Date,Precip Type,Temperature (C),Humidity,Wind Speed (km/h),Wind Bearing (degrees),Visibility (km),Loud Cover,Pressure (millibars)
0,-1.616884,-0.3888,-0.231158,0.809902,0.464373,0.568333,1.505665,0.0,0.102777
1,-1.616884,-0.3888,-0.242933,0.658747,0.485034,0.642394,1.505665,0.0,0.107018
2,-1.616884,-0.3888,-0.240690,0.809902,-0.988796,0.133228,1.281872,0.0,0.109648
3,-1.616884,-0.3888,-0.350583,0.507593,0.462077,0.734969,1.505665,0.0,0.113634
4,-1.616884,-0.3888,-0.303486,0.507593,0.025897,0.642394,1.505665,0.0,0.114483
...,...,...,...,...,...,...,...,...,...
67512,1.581119,-0.3888,0.588555,0.557978,-0.031495,0.827545,0.001284,0.0,0.061385
67513,1.581119,-0.3888,0.585752,0.356438,0.386319,0.734969,0.270664,0.0,0.070291
67514,1.581119,-0.3888,0.528562,0.406823,0.452894,0.651651,1.505665,0.0,0.074702
67515,1.581119,-0.3888,0.362601,0.255669,0.450599,0.559076,1.505665,0.0,0.074786
67516,1.581119,-0.3888,0.253269,0.608362,-0.022313,0.346152,1.281872,0.0,0.083438

In [17]:
regr = linear_model.LinearRegression()
regr.fit (x_train, y_train)
print ('Coefficients: ', regr.coef_)

Coefficients:  [[-3.21825819e-02 -1.46952451e-01  1.10343715e+01  1.67103122e-01
  -7.35554136e-01  5.05207381e-02 -2.99642973e-02  0.00000000e+00
   2.36010852e-04]]

In [18]:
y_pred = regr.predict(x_test)
y_pred = pd.DataFrame(y_pred,columns=['Apparent Temperature (C)'])
y_pred.head(20)

    Apparent Temperature (C)
0                  12.463979
1                  14.004109
2                  16.097718
3                  17.414742
4                  17.961209
5                  19.974491
6                  21.782628
7                  22.064919
8                  22.516535
9                  23.260369
10                 23.412733
11                 23.549617
12                 22.921020
13                 22.993125
14                 19.986309
15                 16.135564
16                 15.750222
17                 13.289024
18                 13.826276
19                 12.695706

In [19]:
# mean_squared_error(y_train, y_pred)
len(y_pred.index)

28936

In [20]:
y_pred.to_csv("weather_pred.csv",index=False)